"""empty message

Revision ID: 91a963f2c8e5
Revises: 1d77b357d84f
Create Date: 2021-05-28 13:57:44.878473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a963f2c8e5'
down_revision = '1d77b357d84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=360),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=360),
               nullable=True)
    # ### end Alembic commands ###
